version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
    ignore:
      # typescript-eslint does not support TS >=7 yet
      # (https://github.com/typescript-eslint/typescript-eslint/issues/10940)
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
